#!/usr/bin/env python3
"""
build.py - Identical Hub V2 Bundler & Validator
Bundles all modular files in v2/ into a single executable local.lua for loader compatibility.
"""

import os
import re
import subprocess
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
V2_DIR = os.path.join(BASE_DIR, "v2")
OUTPUT_FILE = os.path.join(BASE_DIR, "local.lua")

# Module resolution mapping
def get_module_id(filepath):
    rel = os.path.relpath(filepath, V2_DIR)
    if rel == "main.lua":
        return "main"
    mod_id = rel.replace("/", ".").replace("\\", ".")
    if mod_id.endswith(".lua"):
        mod_id = mod_id[:-4]
    return mod_id

def resolve_require(match, current_mod_id):
    raw = match.group(1).strip()
    # e.g. script.Parent.Parent.core.services or script.core.services or script.Parent.tracker
    # Split by '.'
    parts = raw.split(".")
    
    # Calculate current directory parts
    if current_mod_id == "main":
        cur_parts = []
    else:
        cur_parts = current_mod_id.split(".")[:-1] # directory of current file
    
    # Process each token
    target_parts = list(cur_parts)
    for p in parts:
        if p == "script":
            continue
        elif p == "Parent":
            if target_parts:
                target_parts.pop()
        else:
            target_parts.append(p)
            
    target_mod_id = ".".join(target_parts)
    return f'__require("{target_mod_id}")'

def build():
    print("🚀 Starting Identical Hub V2 Modular Build...")
    
    modules = {}
    main_code = ""
    
    for root, _, files in os.walk(V2_DIR):
        for f in files:
            if f.endswith(".lua"):
                full_path = os.path.join(root, f)
                mod_id = get_module_id(full_path)
                with open(full_path, "r", encoding="utf-8") as file:
                    content = file.read()
                
                if mod_id == "main":
                    main_code = content
                else:
                    modules[mod_id] = content

    print(f"📦 Discovered {len(modules)} submodules + main entry point.")
    
    # Transform requires
    require_pattern = re.compile(r'require\s*\(\s*([^)]+)\s*\)')
    
    transformed_modules = {}
    for mod_id, code in modules.items():
        transformed = require_pattern.sub(lambda m: resolve_require(m, mod_id), code)
        transformed_modules[mod_id] = transformed
        
    transformed_main = require_pattern.sub(lambda m: resolve_require(m, "main"), main_code)
    
    # Generate bundle
    bundle_lines = [
        "--[[",
        "    ==================================================================",
        "    IDENTICAL HUB V2 - HEAVYWEIGHT FISHING (MODULAR BUILD)",
        "    Architecture: Modular V2 (Clean State Machine • Strict Combo)",
        "    Auto-generated by build.py - Do not edit directly!",
        "    ==================================================================",
        "--]]",
        "",
        "local __modules = {}",
        "local __cache = {}",
        "local function __require(modName)",
        "    if __cache[modName] ~= nil then",
        "        return __cache[modName]",
        "    end",
        "    local fn = __modules[modName]",
        "    if not fn then",
        '        error("[Identical V2] Module not found: " .. tostring(modName))',
        "    end",
        "    local res = fn()",
        "    __cache[modName] = res",
        "    return res",
        "end",
        ""
    ]
    
    # Add each module definition
    for mod_id in sorted(transformed_modules.keys()):
        bundle_lines.append(f'__modules["{mod_id}"] = function()')
        bundle_lines.append(transformed_modules[mod_id])
        bundle_lines.append("end\n")
        
    bundle_lines.append("-- [[ ENTRY POINT: main.lua ]]")
    bundle_lines.append(transformed_main)
    
    bundle_content = "\n".join(bundle_lines)
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
        out.write(bundle_content)
        
    print(f"✅ Bundle successfully written to: {OUTPUT_FILE} ({len(bundle_content):,} bytes)")
    
    # Syntax check using luac
    luac_path = "/opt/homebrew/bin/luac"
    if os.path.exists(luac_path):
        res = subprocess.run([luac_path, "-p", OUTPUT_FILE], capture_output=True, text=True)
        if res.returncode == 0:
            print("🎉 Syntax validation PASSED! Zero errors found in bundle.")
        else:
            print(f"❌ Syntax validation FAILED:\n{res.stderr}")
            sys.exit(1)
    else:
        print("⚠️ luac not found at /opt/homebrew/bin/luac, skipping local compiler check.")

if __name__ == "__main__":
    build()
